### ISSUE TITLE
 Cannot successfully run graphql codegen, as prisma-binding throws an error

### ISSUE THREAD

**Issue by minheq** [prisma/prisma-binding#192]
Reproduction of the bug:

https://github.com/minheq/prisma-binding-bug

# Bug
Cannot successfully run `graphql codegen`, as `prisma-binding` throws an error

## Reproducing the bug
Clone repo and run following commands

```
yarn
yarn codegen
```

## Expected result
It should generate `schema.ts` file with typescript types/interface for `schema.graphql`, based on `.graphqlconfig.yml`

## Actual Result
Throws an error:

```
$ graphql codegen
warning command prepare both exists in plugin /Users/minheq/Documents/Repositories/prisma-binding-bug/node_modules/graphql-cli-prepare and is shipped with the graphql-cli.
The plugin is being ignored.
✖ Generating bindings for project app...
TypeError: Cannot read property 'type' of undefined
    at getWhere (/Users/minheq/Documents/Repositories/prisma-binding-bug/node_modules/prisma-binding/dist/utils.js:44:9)
    at /Users/minheq/Documents/Repositories/prisma-binding-bug/node_modules/prisma-binding/src/utils.ts:41:12
    at Array.map (<anonymous>)
    at getTypesAndWhere (/Users/minheq/Documents/Repositories/prisma-binding-bug/node_modules/prisma-binding/src/utils.ts:38:21)
    at Object.getExistsTypes (/Users/minheq/Documents/Repositories/prisma-binding-bug/node_modules/prisma-binding/src/utils.ts:9:17)
    at PrismaTypescriptGenerator.renderExists (/Users/minheq/Documents/Repositories/prisma-binding-bug/node_modules/prisma-binding/src/PrismaTypescriptGenerator.ts:71:20)
    at PrismaTypescriptGenerator.render (/Users/minheq/Documents/Repositories/prisma-binding-bug/node_modules/prisma-binding/src/PrismaTypescriptGenerator.ts:19:32)
    at /Users/minheq/Documents/Repositories/prisma-binding-bug/node_modules/prisma-binding/src/bin.ts:69:34
    at step (/Users/minheq/Documents/Repositories/prisma-binding-bug/node_modules/prisma-binding/dist/bin.js:33:23)
    at Object.next (/Users/minheq/Documents/Repositories/prisma-binding-bug/node_modules/prisma-binding/dist/bin.js:14:53)
```

**Comment by medelman17** [comment]
I can reproduce.

@minheq --

If you modify your `buggyTypes` query to include some arguments, it will resolve your issue. For example: 

```
type Query {
  buggyTypes(where: ID!): [BuggyType!]!
}
```

I will work on a PR for this.

**Comment by minheq** [comment]
@medelman17 Great! thanks for the tip :)

**Comment by maticzav** [comment]
Hey @minheq @medelman17 👋,

Can you still reproduce this issue with the latest versions of the stack?

**Comment by artemzakharov** [comment]
@maticzav I just got this issue by having a type with no properties other than `id: ID! @unique` defined in my Prisma schema. The OP's reproduction repo has the same setup, so I think that might be the source of the issue here.

**Comment by maticzav** [comment]
Hey @minheq 👋,

I believe this is a design decision since `prisma-binding` assumes you are using it with Prisma itself where each type also features `where` input argument. I was able to fix the bug by adding `where` in the arguments list.

```graphql
schema {
  query: Query
}

type Query {
  buggyTypes(where: Input!): [BuggyType!]!
}

input Input {
  foo: String
}

type BuggyType {
  id: ID!
}
```

We will discuss the next steps in the upcoming week and change the code accordingly. 🙂

**Comment by minheq** [comment]
i see :)

sounds good to me!

**Comment by maticzav** [comment]
Hey @minheq 👋,

As promised, we discussed your case; `prisma-binding` is designed especially for Prisma. As a consequence, it doesn't work with other non-prisma schemas which you've already experienced. 

I suggest you try using `graphql-binding` instead of `prisma-binding` to solve your problem.

**Comment by minheq** [comment]
Thank you for your response! @maticzav

**Comment by minheq** [comment]
Thank you for your response! @maticzav
