### ISSUE TITLE
Cannot set property 'fragmentReplacements' of undefined

### ISSUE THREAD

**Issue by luandro** [prisma/prisma-binding#248]
I keep gretting this error when trying to use `prisma-binding` in my server.

```
/Users/server/node_modules/graphql-binding/dist/Delegate.js:48
        this.fragmentReplacements = fragmentReplacements || [];
                                  ^

TypeError: Cannot set property 'fragmentReplacements' of undefined
    at Delegate (/Users/server/node_modules/graphql-binding/dist/Delegate.js:48:35)
    at Binding (/Users/server/node_modules/graphql-binding/dist/Binding.js:28:28)
    at Prisma (/Users/server/node_modules/prisma-binding/dist/Prisma.js:54:24)
    at Object.<anonymous> (/Users/server/index.js:23:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

**Comment by maticzav** [comment]
Hey @luandro 👋,

Could you compose a simple reproduction of this bug? It could be either CodeSandbox app or a Github repository. This way we can fix the bug a lot more quickly 🙂

**Comment by luandro** [comment]
Thanks @maticzav, it was happening on [this repo](https://github.com/ewe-kombucha/ewe-server), but I've started a new project that it works without any problems. So I'll close, thanks for the attention.
